Parse files
serverlessworkflow/sdk-go pull request #19
Opened 2020-12-02 11:17 UTC by iwita

**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
In this PR,  the functionality of parsing nested files for events and functions has been added. 

**Special notes for reviewers**:
I added a few more tests for: 
- Reading nested file from url
- Reading nested file from relative path
- Reading nested file from absolute path (in this case I only added the file:// prefix to the relative path, since it depends to the current dir of the user.

**Additional information (if needed):**

2020-12-02 13:18 UTC, ricardozanini commented on model/unmarshal_json.go
> +		s = strings.TrimPrefix(s, "file:/")
Can you please add those to a `const`?

2020-12-02 13:22 UTC, ricardozanini reviewed
Great work, @iwita ! Just one minor thing regarding a constant. Also, can you move the data from `features` package to `testdata` instead? Since these resources are only used in the test cases, I think would be better to leave them there.

Nice test cases btw. Many thanks for this PR!!

2020-12-02 13:43 UTC, iwita commented on model/unmarshal_json.go
> +		s = strings.TrimPrefix(s, "file:/")
Do you mean the prefix "file://"?

2020-12-02 13:45 UTC, iwita commented
Thank you @ricardozanini !
I will add your additional comments.

> Nice test cases btw. Many thanks for this PR!!

I had created another test case for the `file://` prefix but I was able only to test it in my working directory

2020-12-02 14:07 UTC, ricardozanini commented on model/unmarshal_json.go
> +		s = strings.TrimPrefix(s, "file:/")
Yes!

2020-12-02 14:08 UTC, ricardozanini commented
> I had created another test case for the file:// prefix but I was able only to test it in my working directory

np!

> Shoud I follow this pattern in files structure? https://github.com/serverlessworkflow/sdk-java/tree/master/api/src/test/resources

Nops. In our case, `testdata` is the directory to put resources that we only use on test cases. So the files you've added to the `features` directory actually should be in `testdata`. In the files you refer to them just change from `"functions": "features/applicationrequestfunctions.json",` to ` "functions": "testdata/applicationrequestfunctions.json",`. Makes sense?

2020-12-02 14:10 UTC, iwita commented
> Nops. In our case, testdata is the directory to put resources that we only use on test cases. So the files you've added to the features directory actually should be in testdata. In the files you refer to them just change from "functions": "features/applicationrequestfunctions.json", to "functions": "testdata/applicationrequestfunctions.json",. Makes sense?

Yeah, sure. Just double checked it.

2020-12-02 17:44 UTC, ricardozanini approved these changes

2020-12-03 15:58 UTC, ricardozanini requested changes
There's just a script change that we need to revert

2020-12-03 15:58 UTC, ricardozanini commented on hack/generate-spec-types.sh
> +  git clone --single-branch --branch fix-zeros git@github.com:ricardozanini/sw-specification.git ${targetdir}
I believe we need to revert this :)

2020-12-03 18:00 UTC, iwita commented on hack/generate-spec-types.sh
> +  git clone --single-branch --branch fix-zeros git@github.com:ricardozanini/sw-specification.git ${targetdir}
yes, my bad :(

2020-12-03 19:37 UTC, ricardozanini commented
@iwita were you able to run `make addheaders`?

2020-12-04 10:22 UTC, iwita commented
Hi,
> @iwita were you able to run make addheaders?

I just submitted a new commit:
Changed the path of addlicense and clean the local environment afterwards.
However, while this change executes the Makefile successfully locally, it does not pass the automated tests here.

2020-12-04 14:37 UTC, ricardozanini commented
> Hi,
> 
> > @iwita were you able to run make addheaders?
> 
> I just submitted a new commit:
> Changed the path of addlicense and cleaned the local environment afterwards.
> However, while this change executes the Makefile successfully locally, it does not pass the automated tests here.

That's because `GOPATH` is not part of this step in the GH Actions. Can you give a try to this #20? I believe that now you should be able to run the tooling in your local env.

2020-12-04 18:35 UTC, ricardozanini approved these changes

2020-12-04 18:50 UTC, merged